# GUI UPGRADE TO WORD GUESS GAME
import tkinter
import random as rnd
from tkinter import*
root=Tk()
root.title("WORD GUESS GAME")
root.configure(bg="lightblue")
blank,lives="""                                                          
                                                                           
                                                                                  
                                                                            
                                                                            """,10

def liswor():
    tupl_word=(("elegant", "Graceful and stylish \n in appearance or manner."),
    ("harmony", "The combination of different musical\n notes played or sung at the same time."),
    ("dazzling", "Extremely bright and impressive."),
    ("curious", "Eager to know or learn something."),
    ("serenity", "The state of being calm, peaceful, \nand untroubled."),
    ("liberty", "The state of being free within \nsociety from oppressive restrictions."),
    ("vibrant", "Full of energy and life."),
    ("whimsical", "Playfully quaint or fanciful."),
    ("tranquil", "Free from disturbance; calm."),
    ("mystical", "Relating to mystics or religious mysticism."),
    ("dynamic", "Characterized by constant change, \nactivity, or progress."),
    ("radiant", "Sending out light; shining\n or glowing brightly."),
    ("eloquent", "Fluent or persuasive in\n speaking or writing."),
    ("resilient", "Able to withstand or recover \n quickly from difficult conditions."),
    ("audacious", "Showing a willingness to take\n surprisingly bold risks."),
    ("ephemeral", "Lasting for a very short time."),
    ("pristine", "In its original condition; unspoiled."),
    ("melodic", "Having a pleasant tune; tuneful."),
    ("enigmatic", "Difficult to interpret or \nunderstand; mysterious."),
    ("sublime", "Of such excellence or beauty as\n to inspire great admiration."),
    ("radiant", "Sending out light; shining or glowing brightly."),
    ("effusive", "Expressing feelings of\n gratitude, pleasure,\n or approval in an unrestrained manner."),
    ("serendipity", "The occurrence of events by chance\n in a happy or beneficial way."),
    ("fascinate", "To attract the strong attention \nand interest of someone."),
    ("adventurous", "Willing to take risks or try out \nnew methods, ideas, or experiences."),
    ("charismatic", "Exercising a compelling charm \nthat inspires devotion in others."),
    ("vivid", "Producing powerful feelings or strong,\n clear images in the mind."),
    ("gallant", "Brave; heroic."),
    ("intrepid", "Fearless; adventurous."),
    ("luminous", "Full of or shedding light; bright or shining."),
    ("tenacious", "Tending to keep a firm hold of something;\n clinging or adhering closely."),
    ("effervescent", "Vivacious and enthusiastic."),
    ("delightful", "Causing delight; charming."),
    ("mirthful", "Full of mirth; merry or amusing."),
    ("gregarious", "Fond of company; sociable."),
    ("arduous", "Involving or requiring strenuous\n effort; difficult and tiring."),
    ("brilliant", "Exceptionally clever or talented."),
    ("cherish", "To protect and care \nfor someone lovingly."),
    ("devotion", "Love, loyalty, or enthusiasm for\n a person, activity, or cause."),
    ("eclectic", "Deriving ideas, style, or taste from \na broad and diverse range of sources."),
    ("fragrant", "Having a pleasant or sweet smell."),
    ("glorious", "Having, worthy of, or bringing\n fame or admiration."),
    ("harmonious", "Forming a pleasing or consistent whole."),
    ("illustrious", "Well known, respected, and\n admired for past achievements."),
    ("jubilant", "Feeling or expressing great\n happiness and triumph."),
    ("kindhearted", "Having a kind and \nsympathetic nature."),
    ("lucid", "Expressed clearly; easy\n to understand."),
    ("magnanimous", "Generous or forgiving, especially \ntowards a rival or less powerful person."),
    ("nostalgic", "Characterized by or exhibiting\n feelings of nostalgia."),
    ("optimistic", "Hopeful and confident \nabout the future."),
    ("perceptive", "Having or showing \nsensitive insight."),
    ("quaint", "Attractively unusual or\n old-fashioned."),
    ("radiant", "Sending out light; shining\n or glowing brightly."),
    ("spectacular", "Beautiful in a dramatic and eye-catching way."),
    ("tranquility", "The quality or state of\n being tranquil; calm."),
    ("undaunted", "Not intimidated or discouraged \nby difficulty, danger, or disappointment."),
    ("venerable", "Accorded a great deal of respect,\n especially because of age, wisdom, or character."),
    ("wholesome", "Conducive to or suggestive of\n good health and physical well-being."),
    ("yearning", "A feeling of intense\n longing for something."),
    ("zealous", "Having or showing zeal."),
    ("ambitious", "Having or showing a strong desire\n and determination to succeed."),
    ("benevolent", "Well-meaning and kindly."),
    ("chivalrous", "Courteous and gallant,\nespecially towards women."),
    ("dedicated", "Devoted to a task or purpose; \nhaving single-minded loyalty \nor integrity."),
    ("exuberant", "Filled with or characterized by\n a lively energy and excitement."),
    ("flourish", "To grow or develop in a \nhealthy or vigorous way."),
    ("graceful", "Having or showing grace or elegance."),
    ("humble", "Having or showing a modest or \nlow estimate of one's own importance."),
    ("ingenious", "Clever, original, and inventive."),
    ("jovial", "Cheerful and friendly."),
    ("keen", "Having or showing eagerness\n or enthusiasm."),
    ("luminous", "Full of or shedding light \n bright or shining."),
    ("mystic", "Involving or characterized by\n esoteric, otherworldly,\n or symbolic practices or content."),
    ("notable", "Worthy of attention or notice;\n remarkable."),
    ("opulent", "Ostentatiously rich and\n luxurious or lavish."),
    ("pragmatic", "Dealing with things sensibly\n and realistically in a way that\n is based on practical rather than \ntheoretical considerations."),
    ("quixotic", "Exceedingly idealistic; \nunrealistic and impractical."),
    ("resilient", "Able to withstand or recover \nquickly from difficult conditions."),
    ("serene", "Calm, peaceful, and\n untroubled; tranquil."),
    ("tenacious", "Tending to keep a firm\n hold of something \n clinging or adhering closely."),
    ("undaunted", "Not intimidated or discouraged by\n difficulty, danger, or disappointment."),
    ("versatile", "Able to adapt or be adapted to\n many different functions or activities."),
    ("whimsical", "Playfully quaint or fanciful,\n especially in an appealing\n and amusing way."),
    ("xenial", "Hospitable, especially to visiting\n strangers or foreigners."),
    ("youthful", "Young or seeming young."),
    ("zealous", "Having or showing zeal."),("ace", "A person who excels at a \nparticular activity."),
    ("bat", "A nocturnal flying mammal."),
    ("cap", "A head covering."),
    ("dot", "A small round mark."),
    ("egg", "A round or oval object laid \nby a female bird."),
    ("fan", "A device for creating\nn a current of air."),
    ("gap", "An unfilled space or interval."),
    ("hat", "A shaped covering for the head."),
    ("ice", "Frozen water."),
    ("jam", "A sweet spread made from fruit."),
    ("kit", "A set of tools or equipment."),
    ("log", "A part of the trunk or a\n large branch of a tree."),
    ("map", "A representation of\n an area of land or sea."),
    ("net", "A mesh fabric used \nfor catching fish."),
    ("oak", "A type of tree known\n for its strength."),
    ("pen", "An instrument for\n writing or drawing."),
    ("quill", "A pen made from a feather."),
    ("run", "To move swiftly on foot."),
    ("sun", "The star at the center\n of the solar system."),
    ("tap", "A device by which a flow of liquid\n or gas from a pipe or container\n can be controlled."),
    ("urn", "A tall, rounded vase \nwith a base."),
    ("vet", "A doctor who treats animals."),
    ("web", "A network of fine threads\n constructed by a spider."),
    ("yak", "A long-haired bovine found\nin the Himalayas."),
    ("zip", "To fasten with a zipper."),
    ("aim", "To point or direct \nat a target."),
    ("bug", "An insect or germ."),
    ("cat", "A small domesticated\ncarnivorous mammal."),
    ("dig", "To break up and move\nearth with a tool."),
    ("elf", "A small supernatural being."),
    ("fig", "A type of fruit."),
    ("gym", "A place equipped for\n physical exercise."),
    ("hop", "To jump lightly."),
    ("ink", "A colored fluid used\nfor writing or drawing."),
    ("jar", "A cylindrical container."),
    ("key", "A small piece of shaped\nmetal used to open a lock."),
    ("lid", "A removable or hinged \ncover for a container."),
    ("mix", "To combine or blend\n into one mass."),
    ("nod", "To move the head up and down."),
    ("owl", "A nocturnal bird of prey."),
    ("pit", "A large hole in the ground."),
    ("ram", "A male sheep."),
    ("sip", "To drink something by \ntaking small mouthfuls."),
    ("toy", "An object for a child \nto play with."),
    ("urn", "A large decorative vase,\n often with a cover."),
    ("vet", "A doctor for animals."),
    ("wig", "A covering for the head made\n of real or artificial hair."),
    ("zap", "To destroy or obliterate."),
    ("act", "To take action."),
    ("bee", "An insect known for its\n role in pollination."),
    ("cub", "A young carnivorous mammal."),
    ("dew", "Tiny drops of water that \nform on cool surfaces."),
    ("eel", "A long, slender fish."),
    ("fox", "A wild animal of the dog family."),
    ("gut", "The stomach or belly."),
    ("hut", "A small, simple, single-story\n house or shelter."),
    ("jet", "A fast aircraft."),
    ("kid", "A young goat or a child."),
    ("lip", "The edge of the mouth."),
    ("man", "An adult male human."),
    ("nut", "A fruit composed of a hard\n shell and a seed."),
    ("owl", "A nocturnal bird of prey."),
    ("pan", "A container used for cooking."),
    ("rat", "A rodent that resembles\n a large mouse."),
    ("sea", "A large body of saltwater."),
    ("top", "The highest point or part."),
    ("van", "A medium-sized road vehicle."),
    ("win", "To achieve victory."),
    ("zip", "To fasten with a zipper."),("acid", "A substance with a sour taste."),
    ("bark", "The outer covering\n of a tree."),
    ("clue", "A piece of evidence \nor information."),
    ("dusk", "The time just before night."),
    ("echo", "A sound that reflects back."),
    ("fern", "A type of green plant."),
    ("glow", "To emit a steady light."),
    ("haze", "A slight obscuration\n of the air."),
    ("idol", "An image or \nrepresentation of a god."),
    ("jest", "A thing said or \ndone for amusement."),
    ("keen", "Having or showing\n eagerness."),
    ("lure", "Something that\n tempts or attracts."),
    ("mint", "A place where money\n is coined."),
    ("nest", "A structure built\n by birds."),
    ("oath", "A solemn promise."),
    ("perk", "A benefit or advantage."),
    ("quiz", "A test of knowledge."),
    ("reef", "A ridge of rock in the sea."),
    ("silk", "A fine, soft fiber\n produced by silkworms."),
    ("twig", "A small thin branch\n of a tree."),
    ("urge", "A strong desire\n or impulse."),
    ("veil", "A piece of cloth \nworn over the face."),
    ("wisp", "A small thin or\n twisted bunch."),
    ("yarn", "Spun thread used \nfor knitting."),
    ("zeal", "Great energy or enthusiasm."),
    ("aloe", "A plant with thick \nfleshy leaves."),
    ("blip", "A small spot of light\n on a radar screen."),
    ("chop", "To cut with a quick,\n heavy blow."),
    ("dome", "A rounded vault\n forming the roof."),
    ("etch", "To engrave a design\n on a surface."),
    ("fume", "Gas or vapor with \na strong smell."),
    ("glum", "Looking or feeling dejected."),
    ("hymn", "A religious song or poem."),
    ("inch", "A unit of length."),
    ("jolt", "A sudden rough or\n violent movement."),
    ("kite", "A toy flown in the wind."),
    ("lace", "A fine open fabric \nof cotton or silk."),
    ("moat", "A deep, wide ditch\n surrounding a castle."),
    ("numb", "Deprived of the power\n of sensation."),
    ("omen", "An event regarded as\n a portent."),
    ("plow", "A tool used for farming."),
    ("quip", "A witty remark."),
    ("rant", "To speak or shout at length."),
    ("soar", "To fly or rise high in the air."),
    ("tide", "The rise and fall \nof sea levels."),
    ("urge", "A strong desire or impulse."),
    ("vain", "Having an excessively \nhigh opinion of oneself."),
    ("whip", "A strip of leather \nused for striking."),
    ("yawn", "To open the mouth wide \nwith a deep breath."),
    ("zest", "Great enthusiasm and energy."),
    ("arch", "A curved symmetrical structure."),
    ("blow", "A strong wind."),
    ("crux", "The most important point."),
    ("dawn", "The first appearance of\n light in the morning."),
    ("elm", "A type of tree."),
    ("foam", "A mass of small bubbles."),
    ("grit", "Small loose particles\n of stone or sand."),
    ("hull", "The main body of a ship."),
    ("jazz", "A style of music\n characterized by swing."),
    ("knit", "To make a garment by\n interlocking loops of wool."),
    ("lamb", "A young sheep."),
    ("moan", "A long, low sound \nexpressing pain or sorrow."),
    ("nerd", "A person who is\n overly intellectual."),
    ("peel", "To remove the outer\n covering of something."),
    ("quip", "A witty remark."),
    ("rust", "A reddish-brown substancen\n on iron."),
    ("sail", "A piece of material\n extended on a ship."),
    ("toil", "To work extremely hard."),
    ("urge", "A strong desire or impulse."),
    ("vain", "Having an excessively\n high opinion of oneself."),
    ("weep", "To shed tears."),
    ("yelp", "A short, sharp cry."),
    ("zeal", "Great energy or enthusiasm."),
    ("apex", "The top or highest\n part of something."),
    ("bard", "A poet, traditionally \none reciting epics."),
    ("crop", "A cultivated plant that\n is grown as food."),
    ("duel", "A contest with deadly \nweapons arranged between\n two people."),
    ("echo", "A sound that reflects back."),
    ("flap", "To move up and down \nor back and forth."),
    ("glee", "Great delight."),
    ("harp", "A stringed musical instrument."),
    ("jolt", "A sudden rough or\n violent movement."),
    ("knot", "A fastening made by looping a piece of string."),
    ("lava", "Hot molten rock\n erupted from a volcano."),
    ("mist", "A fine spray or light fog."),
    ("nail", "A small metal spike\n used for fastening."),
    ("puff", "A short, explosive\n burst of breath or wind."),
    ("rant", "To speak or shout at length."),
    ("scar", "A mark left on the skin\n after a wound has healed."),
    ("trot", "To proceed at a pace\n faster than a walk."),
    ("vain", "Having an excessively\n high opinion of oneself."),
    ("warp", "To become or cause to \nbecome bent or twisted."),
    ("yell", "To shout loudly."),
    ("zeal", "Great energy or enthusiasm."),
    ("axis", "An imaginary line about\n which a body rotates."),
    ("bell", "A hollow instrument that\n rings when struck."),
    ("clay", "A stiff, sticky earth used \nin making bricks and pottery."),
    ("dusk", "The time just before night."),
    ("envy", "A feeling of discontented\n or resentful longing."),
    ("fist", "A hand with the fingers clenched."),
    ("glow", "To emit a steady light."),
    ("hemp", "A plant used to make fibers."),
    ("jazz", "A style of music \ncharacterized by swing."),
    ("king", "A male ruler of an\n independent state."),
    ("leap", "To jump or spring a long way."),
    ("moth", "An insect with wings that\n is attracted to light."),
    ("nest", "A structure built by birds."),
    ("perk", "A benefit or advantage."),
    ("quiz", "A test of knowledge."),
    ("riff", "A short repeated phrase\n in popular music."),
    ("soak", "To make or allow something\n to become thoroughly wet."),
    ("twig", "A small thin branch of a tree."),
    ("urge", "A strong desire or impulse."),
    ("void", "Completely empty."),
    ("whip", "A strip of leather used \nfor striking."),
    ("yoke", "A wooden crosspiece fastened\n over the necks of two animals."),
    ("zeal", "Great energy or enthusiasm."),
    ("amid", "Surrounded by; in the \nmiddle of."),
    ("bolt", "A metal pin or bar that\n slides into a socket."),
    ("coin", "A flat, typically round\n piece of metal used as money."),
    ("dash", "To run or travel somewhere\n in a great hurry."),
    ("earn", "To receive money in return\n for labor or services."),
    ("flaw", "A mark, fault, or other\n imperfection."),
    ("glad", "Feeling pleasure or happiness."),
    ("herb", "A plant used for medicinal\n or culinary purposes."),
    ("jump", "To push oneself off a\n surface and into the air."),
    ("kind", "Having a friendly, generous,\n or considerate nature."),
    ("lush", "Growing luxuriantly."),
    ("mock", "To tease or laugh at in\n a scornful manner."),
    ("node", "A point in a network at\n which lines intersect."),
    ("palm", "The inner surface of the hand."),
    ("quay", "A platform lying alongside or\n projecting into water\n for loading and unloading ships."),
    ("rock", "The solid mineral material\n forming part of the\n surface of the earth."),
    ("spur", "A thing that prompts or\n encourages someone."),
    ("tame", "Not dangerous or frightened\n of people."),
    ("vent", "An opening that allows air,\n gas, or liquid to pass out of\n or into a confined space."),
    ("wade", "To walk through water or another liquid."),
    ("yawn", "To open the mouth wide\n and take a deep breath."),
    ("zest", "Great enthusiasm and energy."),
    ("atom", "The basic unit of a\n chemical element."),
    ("bend", "To shape or force something \nstraight into a curve or angle."),
    ("chat", "To talk in a friendly\n and informal way."),
    ("drop", "To let or make something fall."),
    ("edge", "The outside limit of an object."),
    ("flow", "To move along in a steady,\n continuous stream."),
    ("grin", "To smile broadly."),
    ("hush", "To make someone be \nquiet or stop talking."),
    ("join", "To connect or fasten\n things together."),
    ("lamp", "A device for giving light."),
    ("mine", "A type of excavation\n in the earth."),
    ("nest", "A structure built by birds."),
    ("pond", "A small body of still water."),
    ("quip", "A witty remark."),
    ("reel", "A cylinder on which film,\n wire, or thread can be wound."),
    ("stir", "To move a spoon or other \nimplement around in a liquid."),
    ("tide", "The rise and fall of sea levels."),
    ("veil", "A piece of cloth worn\n over the face."),
    ("wind", "Air in natural motion."),
    ("yoke", "A wooden crosspiece fastened\n over the necks of two animals."),
    ("zeal", "Great energy or enthusiasm."),("absorb", "To take in or soak up."),
    ("ballad", "A poem or song narrating a \n story in short stanzas."),
    ("canyon", "A deep gorge, typically one \n with a river flowing through it."),
    ("decade", "A period of ten years."),
    ("embark", "To begin a journey or course \n of action."),
    ("fabric", "Material made by weaving,\n knitting, or felting fibers."),
    ("galaxy", "A system of millions or \n billions of stars."),
    ("hacker", "A person who uses computers \n to gain unauthorized \naccess to data."),
    ("impact", "The action of one object \n coming forcibly into \ncontact with another."),
    ("jigsaw", "A puzzle consisting of \n small pieces that fit together."),
    ("knight", "A man who served his lord \n as a mounted soldier."),
    ("lizard", "A reptile with a long body \n and tail, four legs,\n and scaly skin."),
    ("module", "A self-contained component \n of a system."),
    ("neuron", "A nerve cell that is the \n basic building block \nof the nervous system."),
    ("orange", "A round juicy citrus fruit \n with a tough bright\n reddish-yellow rind."),
    ("plasma", "The colorless fluid part of \n blood, lymph, or milk."),
    ("quartz", "A hard mineral consisting of \n silica, found widely\n in igneous, metamorphic, and \n sedimentary rocks."),
    ("rhythm", "A strong, regular repeated \n pattern of movement or sound."),
    ("spiral", "A shape made by a curve that \n winds around a central point."),
    ("thrill", "A sudden feeling of \n excitement and pleasure."),
    ("utopia", "An imagined place or state \n of things in which\n everything is perfect."),
    ("voyage", "A long journey involving \n travel by sea or in space."),
    ("wreath", "An arrangement of flowers, \n leaves, or stems fastened\n in a ring."),
    ("zenith", "The highest point reached by \n a celestial or other object."),
    ("abduct", "To take someone away \n illegally by force."),
    ("ballot", "A process of voting, in \n writing and typically\n in secret."),
    ("castle", "A large building typically \n of the medieval period."),
    ("demand", "An insistent request, made \n as of right."),
    ("enable", "To give someone the \n authority or means to do something."),
    ("fusion", "The process or result of \n joining two or more\n things together to form a \n single entity."),
    ("gossip", "Casual or unconstrained \n conversation about\n other people."),
    ("huddle", "To crowd together."),
    ("insist", "To demand something forcefully."),
    ("juggle", "To continuously toss into \n the air and catch."),
    ("kitten", "A young cat."),
    ("legend", "A traditional story \n sometimes regarded as \nhistorical but not authenticated."),
    ("mentor", "An experienced and trusted \n adviser."),
    ("notion", "A conception of or belief \n about something."),
    ("ornate", "Made in an intricate shape \n or decorated with complex\n patterns."),
    ("pirate", "A person who attacks and \n robs ships at sea."),
    ("quiver", "To tremble or shake with a \n slight rapid motion."),
    ("rescue", "To save someone from a \n dangerous or distressing \nsituation."),
    ("socket", "A natural or artificial \n hollow into which something fits."),
    ("throne", "A ceremonial chair for a \n sovereign."),
    ("unveil", "To remove a veil or \n covering from."),
    ("victor", "A person who defeats an \n enemy or opponent."),
    ("warmth", "The quality, state, or \n sensation of being warm."),
    ("youths", "The period between \n childhood and adult age."),
    ("abroad", "In or to a foreign country \n or countries."),
    ("beacon", "A fire or light set up in a \n high or prominent position \nas a warning or signal."),
    ("cancel", "To decide or announce that \n a planned event will not\n take place."),
    ("devote", "To give all or a large part \n of one's time or resources \nto a person, activity, or cause."),
    ("export", "To send goods or services \n to another country for sale."),
    ("garlic", "A strong-smelling pungent- \n tasting bulb used as a\n flavoring in cooking."),
    ("horror", "An intense feeling of fear, \n shock, or disgust."),
    ("inject", "To drive or force a liquid, \n especially a drug or vaccine,\n into a person or animal's body\n with a syringe or similar device."),
    ("jungle", "An area of land overgrown \n with dense forest and\n tangled vegetation."),
    ("kidnap", "To abduct someone and hold \n them captive."),
    ("linear", "Arranged in or extending \n along a straight line."),
    ("manual", "Of or done with the hands."),
    ("napkin", "A square piece of cloth or \n paper used at a meal to\n wipe the fingers or lips."),
    ("oracle", "A priest or priestess \n acting as a medium through whom\n advice or prophecy \n was sought from the gods."),
    ("planet", "A celestial body moving in \n an elliptical orbit \naround a star."),
    ("ripple", "A small wave or series of \n waves on the surface of water."),
    ("sparse", "Thinly dispersed or \n scattered."),
    ("tackle", "To make determined efforts \n to deal with a problem\n or difficult task."),
    ("unison", "Simultaneous performance or \n utterance of action or speech."),
    ("verify", "To make sure or demonstrate \n that something is true,\n accurate, or justified."),
    ("wealth", "An abundance of valuable \n possessions or money."),
    ("yellow", "A color like that of egg \n yolk or gold."),
    ("absent", "Not present in a place, at \n an occasion, or as\n part of something."),
    ("burrow", "A hole or tunnel dug by a \n small animal."),
    ("custom", "A traditional and widely \n accepted way of behaving \nor doing something."),
    ("dynamo", "A machine for converting \n mechanical energy into\n electrical energy."),
    ("flavor", "The distinctive taste of a \n food or drink."),
    ("glance", "To take a brief or hurried \n look."),
    ("hunger", "A feeling of discomfort or \n weakness caused by lack of food."),
    ("infuse", "To fill or pervade with a \n quality or feeling."),
    ("jigsaw", "A puzzle consisting of \n small pieces that fit together."),
    ("kidney", "Each of a pair of organs in \n the abdominal cavity\n of mammals, birds, and \n reptiles, excreting urine."),
    ("lethal", "Sufficient to cause death."),
    ("medley", "A varied mixture of people \n or things."),
    ("nugget", "A small lump of gold or \n other precious metal found \nready-formed in the earth."),
    ("occult", "Supernatural, mystical, or \n magical beliefs, practices,\n or phenomena."),
    ("pursue", "To follow someone or \n something in order to\n catch or attack them."),
    ("quench", "To satisfy one's thirst."),
    ("rocket", "A cylindrical projectile \n that can be propelled to\n a great height or distance."),
    ("subtle", "So delicate or precise as \n to be difficult to\n analyze or describe."),
    ("turban", "A man's headdress, worn \n chiefly by Muslims."),
    ("unrest", "A state of dissatisfaction, \n disturbance, and agitation."),
    ("volume", "The amount of space that a \n substance or object occupies."),
    ("wonder", "A feeling of surprise \n mingled with admiration, caused by \nsomething beautiful, unexpected,\n unfamiliar, or inexplicable."),
    ("zygote", "A diploid cell resulting \n from the fusion of two haploid\n gametes; a fertilized ovum."),
    ("anthem", "A rousing or uplifting song \n identified with a particular \ngroup, body, or cause."),
    ("blight", "A plant disease, typically \n one caused by fungi such \nas mildews, rusts, and \n smuts."),
    ("charge", "To demand (an amount) as a \n price from someone for\n a service rendered\n or goods supplied."),
    ("depart", "To leave, typically in order \n to start a journey."),
    ("embody", "To be an expression of or \n give a tangible or visible\n form to an idea, quality,\n or feeling."),
    ("freeze", "To become hardened into ice \n or another solid as\n a result of cold."),
    ("genome", "The complete set of genes \n or genetic material present\n in a cell or \n organism."),
    ("honest", "Free of deceit and \n untruthfulness; sincere."),
    ("inform", "To give someone facts or \n information; to tell."),
    ("jockey", "A person who rides in horse \n races, especially as\n a profession."),
    ("lively", "Full of life and energy; \n active and outgoing."),
    ("mingle", "To mix or cause to mix \n together."),
    ("notice", "Attention; observation."),
    ("oxygen", "A chemical element with the \n symbol O and atomic number 8."),
    ("pocket", "A small pouch inside a \n garment for carrying \nsmall articles."),
    ("radius", "A straight line from the \n center to the circumference\n of a circle or sphere."),
    ("safety", "The condition of being \n protected from or unlikely to \ncause danger, risk, or injury."),
    ("turkey", "A large bird native to \n North America, with a bald\n head and (in the male)\n red wattles."),
    ("upward", "Moving or directed toward a \n higher place or position."),
    ("vendor", "A person or company \n offering something for sale,\n especially a trader in\n the street."),
    ("whiten", "To make or become white."),
    ("zephyr", "A soft gentle breeze."),
    ("archer", "A person who shoots with a \n bow and arrows, especially \nat a target for sport."),
    ("breeze", "A gentle wind."),
    ("create", "To bring something into \n existence."),
    ("demand", "An insistent and \n peremptory request, \nmade as of right."),
    ("enrich", "To improve or enhance the \n quality or value of."),
    ("famous", "Known about by many \n people."),
    ("gather", "To come together; to \n assemble or accumulate."),
    ("happen", "To take place; to occur."),
    ("invest", "To expend money with the \n expectation of achieving \na profit."),
    ("jungle", "An area of land overgrown \n with dense forest and\n tangled vegetation."),
    ("laptop", "A computer that is portable \n and suitable for\n use while traveling."),
    ("marble", "A hard crystalline metamorphic \n form of limestone."),
    ("number", "An arithmetical value, \n expressed by a word,\n symbol, or figure."),
    ("outlet", "A pipe or hole through \n which water or\n gas may escape."),
    ("ponder", "To think about something \n carefully."),
    ("random", "Made, done, happening, or \n chosen without method\n or conscious decision."),
    ("scroll", "A roll of parchment or \n paper for writing or painting on."),
    ("tenant", "A person who occupies land \n or property rented from a landlord."),
    ("update", "To make something more \n modern or up to date."),
    ("wander", "To walk or move in a \n leisurely, casual,\n or aimless way."),
    ("yellow", "A color like that of egg \n yolk or gold."),
    ("advice", "Guidance or recommendations \n concerning prudent future action."),
    ("burden", "A load, especially a heavy \n one."),
    ("cradle", "An infant's bed or crib, \n typically one mounted on rockers."),
    ("divide", "To separate or be separated \n into parts."),
    ("engage", "To participate or become \n involved in."),
    ("forbid", "To refuse to allow \n something."),
    ("golden", "Made of or resembling gold."),
    ("hammer", "A tool with a heavy metal \n head mounted at rightn\n angles at the end of a \n handle."),
    ("inward", "Directed or proceeding \n toward the inside;\n coming in from outside."),
    ("jigsaw", "A puzzle consisting of \n small pieces that fit together."),
    ("locate", "To discover the exact place \n or position of."),
    ("mother", "A woman in relation to her \n child or children."),
    ("narrow", "Of small width in relation \n to length."),
    ("online", "Controlled by or connected \n to another computer\n or to a network."),
    ("polish", "To make the surface of \n something smooth and\n shiny by rubbing it."),
    ("relate", "To make or show a \n connection between."),
    ("school", "An institution for \n educating children."),
    ("tunnel", "An artificial underground \n passage, especially one built\n through a hill or under\n a building, road, or river."),
    ("uproot", "To pull something, \n especially a tree or plant, out of the ground."),
    ("wholly", "Entirely; fully."),
    ("zealot", "A person who is fanatical \n and uncompromising in pursuit\n of their religious, political,\n or other ideals."),("apple", "A round fruit with a \n crisp, sweet taste."),
    ("beach", "A sandy or pebbly shore."),
    ("craft", "An activity involving \n skill in making things."),
    ("dream", "A series of thoughts, \n images, and sensations."),
    ("eagle", "A large bird of prey \n with a massive hooked beak."),
    ("flame", "A hot glowing body of \n ignited gas."),
    ("grape", "A small, round fruit \n typically used in wine."),
    ("haste", "Excessive speed or \n urgency of movement."),
    ("ivory", "A hard, white material \n from elephant tusks."),
    ("jolly", "Happy and cheerful."),
    ("kneel", "To go down on one's \n knee(s)."),
    ("latch", "A metal bar with a \n catch and lever."),
    ("mount", "To climb up or onto \n something."),
    ("nurse", "A person trained to \n care for the sick."),
    ("ocean", "A vast body of salt \n water covering most of Earth."),
    ("pearl", "A smooth, rounded \n bead formed in an oyster."),
    ("quilt", "A warm bed cover made \n of padding enclosed between layers of fabric."),
    ("raven", "A large, black bird \n with a straight bill."),
    ("sheep", "A farm animal with a \n woolly coat."),
    ("trunk", "The main stem of a \n tree."),
    ("uncle", "A brother of one's \n parent."),
    ("vivid", "Producing powerful \n feelings or clear images."),
    ("wrist", "The joint between the \n hand and the forearm."),
    ("yield", "To produce or provide \n something."),
    ("zebra", "A wild horse with \n black-and-white stripes."),
    ("aloud", "Spoken out loud; not \n silently."),
    ("brave", "Ready to face danger \n or pain; courageous."),
    ("charm", "The power of pleasing \n or attracting others."),
    ("dodge", "To avoid by moving \n quickly aside."),
    ("elbow", "The joint between the \n forearm and the upper arm."),
    ("feast", "A large meal, \n typically a celebratory one."),
    ("globe", "A spherical model of \n Earth."),
    ("hinge", "A movable joint or \n mechanism."),
    ("itchy", "Having an irritating \n sensation."),
    ("joker", "A person who jokes \n or fools around."),
    ("knead", "To press and fold \n dough."),
    ("lemon", "A yellow citrus fruit \n with sour juice."),
    ("magic", "The use of charms or \n spells believed to have \n supernatural power."),
    ("nifty", "Particularly good, \n skillful, or effective."),
    ("otter", "A semi-aquatic fish-\n eating mammal."),
    ("pouch", "A small bag or \n sack."),
    ("quack", "The sound a duck \n makes."),
    ("rouge", "A red powder used as \n makeup."),
    ("shark", "A large predatory \n fish."),
    ("torch", "A portable means of \n illumination."),
    ("ulcer", "A sore on the skin or \n a mucous membrane."),
    ("vital", "Absolutely necessary \n or important."),
    ("witty", "Showing or \n characterized by quick and \n inventive humor."),
    ("xenon", "A chemical element \n used in lamps and \n anesthetics."),
    ("yacht", "A medium-sized \n sailboat for cruising or \n racing."),
    ("zesty", "Having a strong, \n pleasant, and somewhat \n spicy flavor."),
    ("amber", "A yellowish-brown \n fossil resin."),
    ("bloom", "The state of having \n flowers in full beauty."),
    ("clash", "A conflict or \n disagreement."),
    ("drift", "To be carried slowly \n by a current."),
    ("elite", "A select group \n regarded as superior."),
    ("froze", "Past tense of freeze; \n turned to ice."),
    ("grill", "A metal framework \n used for cooking."),
    ("haste", "Urgent speed of \n movement."),
    ("inbox", "A place where \n incoming messages are \n received."),
    ("jewel", "A precious stone."),
    ("knock", "To strike a surface \n noisily to attract \n attention."),
    ("lunar", "Relating to the \n moon."),
    ("moist", "Slightly wet; damp."),
    ("nylon", "A synthetic fabric."),
    ("optic", "Relating to vision or \n sight."),
    ("prawn", "A large shrimp."),
    ("query", "A question or inquiry."),
    ("razor", "A tool used for \n shaving hair."),
    ("salty", "Tasting of, \n containing, or \n preserved with salt."),
    ("tiger", "A large wild cat with \n a striped coat."),
    ("under", "Situated below or \n lower than something."),
    ("vocal", "Relating to the \n voice."),
    ("whale", "A large marine mammal \n with a streamlined body."),
    ("xylem", "The vascular tissue in \n plants that conducts \n water."),
    ("yield", "To give way or \n surrender."),
    ("aglow", "Glowing with light or \n color."),
    ("blend", "To mix together \n thoroughly."),
    ("crush", "To press or squeeze \n with force."),
    ("doubt", "A feeling of \n uncertainty or lack of \n conviction."),
    ("earth", "The planet we live \n on."),
    ("frost", "A deposit of small \n white ice crystals."),
    ("glint", "A small flash of \n light."),
    ("harsh", "Unpleasantly rough or \n jarring to the senses."),
    ("ivory", "A hard white substance \n from the tusks of \n elephants."),
    ("jolly", "Happy and cheerful."),
    ("knack", "An acquired or natural \n skill at something."),
    ("loyal", "Giving or showing \n firm and constant \n support."),
    ("magic", "The power of \n apparently influencing \n events."),
    ("nymph", "A mythological spirit \n of nature."),
    ("optic", "Of or relating to the \n eye or vision."),
    ("pupil", "The black circular \n opening in the center of \n the iris."),
    ("queen", "A female ruler of a \n country."),
    ("rider", "A person who rides a \n horse or other animal."),
    ("stark", "Severe or bare in \n appearance."),
    ("table", "A piece of furniture \n with a flat top."),
    ("unity", "The state of being \n united or joined as a \n whole."),
    ("vault", "A large room or \n chamber used for \n storage."),
    ("white", "The color of milk or \n fresh snow."),
    ("youth", "The period between \n childhood and adult age."),
    ("zonal", "Relating to or \n affecting a zone."),
    ("amber", "A fossil resin used in \n jewelry."),
    ("brief", "Of short duration."),
    ("clown", "A comic entertainer."),
    ("draft", "A preliminary version \n of a written work."),
    ("enjoy", "To take delight or \n pleasure in."),
    ("fluid", "A substance that has \n no fixed shape."),
    ("grace", "Simple elegance or \n refinement of movement."),
    ("hatch", "To emerge from an \n egg."),
    ("inlet", "A small arm of the \n sea, a lake, or a river."),
    ("judge", "A public officer \n appointed to decide cases \n in a court of law."),
    ("kinky", "Involving or given to \n unusual sexual behavior."),
    ("latch", "A fastening for a door \n or gate."),
    ("moose", "A large deer with \n broad, flat antlers."),
    ("noble", "Having or showing fine \n personal qualities."),
    ("ocean", "A vast body of salt \n water."),
    ("pride", "A feeling of deep \n pleasure or satisfaction."),
    ("quote", "To repeat words from a \n book or author."),
    ("risky", "Full of the possibility \n of danger."),
    ("stout", "Somewhat fat or heavy \n build."),
    ("tight", "Fixed or fastened \n firmly."),
    ("urban", "Relating to a city or \n town."),
    ("vivid", "Producing powerful \n feelings or strong images."),
    ("waste", "To use or expend \n carelessly."),
    ("xenon", "A chemical element of \n atomic number 54."),
    ("young", "Having lived or \n existed for a short \n time."),
    ("zonal", "Relating to a zone."),
    ("abide", "To accept or act in \n accordance with."),
    ("batch", "A quantity of goods \n produced at one time."),
    ("chase", "To pursue in order to \n catch."),
    ("dwell", "To live or stay as a \n permanent resident."),
    ("exile", "The state of being \n barred from one's native \n country."),
    ("foyer", "An entrance hall or \n other open area."),
    ("gloss", "A shine or luster on a \n smooth surface."),
    ("horde", "A large group of \n people."),
    ("ideal", "A standard of \n perfection."),
    ("junta", "A military or \n political group ruling a \n country after taking \n power by force."),
    ("knoll", "A small hill or \n mound."),
    ("lofty", "Of imposing height."),
    ("medal", "A metal disc awarded \n as a distinction."),
    ("nymph", "A spirit of nature \n envisaged as a beautiful \n maiden."),
    ("obese", "Grossly fat or \n overweight."),
    ("prank", "A practical joke or \n mischievous act."),
    ("query", "A question or request \n for information."),
    ("ridge", "A long, narrow hilltop \n or mountain range."),
    ("stomp", "To tread heavily or \n noisily."),
    ("trend", "A general direction in \n which something is \n developing."),
    ("ultra", "Beyond what is \n ordinary or extreme."),
    ("vowel", "A speech sound \n produced without \n blocking the breath \n channel."),
    ("wrath", "Extreme anger."),
    ("xerox", "A brand name often \n used as a verb meaning to \n copy."),
    ("yacht", "A medium-sized \n sailboat."),
    ("zonal", "Relating to a zone."),
    ("abide", "To tolerate or endure."),
    ("blaze", "A bright flame or \n fire."),
    ("clerk", "A person employed in \n an office."),
    ("drama", "A composition in \n prose or verse."),
    ("erupt", "To explode or burst \n forth."),
    ("frail", "Physically weak or \n delicate."),
    ("grasp", "To seize and hold \n firmly."),
    ("hymen", "A membrane that \n partially closes the \n opening of the vagina."),
    ("input", "Data entered into a \n computer or system."),
    ("joint", "A point at which \n parts are connected."),
    ("knack", "A natural skill or \n talent."),
    ("lunar", "Of or relating to the \n moon."),
    ("match", "A contest between \n persons or teams."),
    ("nudge", "To push gently."),
    ("orbit", "The curved path of a \n celestial object."),
    ("prism", "A solid geometric \n figure with two similar \n ends."),
    ("quart", "A unit of liquid \n capacity."),
    ("reign", "Hold royal office."),
    ("squad", "A small group of \n people having a \n particular task."),
    ("tango", "A ballroom dance of \n Latin-American origin."),
    ("unfit", "Not of the necessary \n quality or standard."),
    ("vapor", "A substance in the \n gas phase."),
    ("whelp", "A young offspring of \n a mammal."),
    ("xenia", "Hospitality, \n especially towards \n strangers."),
    ("yoked", "Joined or linked \n together."),
    ("zoned", "Divided into zones."),("accuracy", "The quality or state of \n being correct or precise."),
    ("backyard", "A yard at the rear of a \n house."),
    ("caboodle", "The whole lot or crowd \n of something."),
    ("delicate", "Easily broken or \n damaged; fragile."),
    ("elevated", "Situated or placed \n higher than the \n surrounding area."),
    ("feedback", "Information about \n reactions to a product, \n used as a basis for \n improvement."),
    ("generous", "Showing a readiness to \n give more of something, \n such as money or time."),
    ("hesitant", "Tentative or unsure \n about taking action."),
    ("imposter", "A person who pretends \n to be someone else."),
    ("jubilant", "Feeling or expressing \n great happiness."),
    ("keyboard", "A panel of keys for \n typing on a computer."),
    ("laughter", "The action or sound of \n laughing."),
    ("mountain", "A large natural \n elevation of the earth's \n surface."),
    ("necklace", "A piece of jewelry \n worn around the neck."),
    ("overcome", "To succeed in dealing \n with a problem."),
    ("passport", "An official document \n issued by a country to \n its citizens."),
    ("radiator", "A device for heating a \n room, or cooling an \n engine."),
    ("scramble", "To move quickly or \n awkwardly up a steep \n slope or over rough \n ground."),
    ("teaspoon", "A small spoon used for \n stirring or eating."),
    ("umbrella", "A device used for \n protection against rain \n or sunlight."),
    ("vacation", "An extended period of \n leisure or recreation."),
    ("wildlife", "Animals that live in \n their natural environment."),
    ("yardstick", "A measuring rod a yard \n long, used for lengths."),
    ("appetite", "A natural desire to \n satisfy a bodily need, \n especially for food."),
    ("birthday", "The anniversary of \n someone's birth."),
    ("collapse", "To fall down or give \n way suddenly."),
    ("diameter", "A straight line passing \n through the center of a \n circle."),
    ("estimate", "An approximate \n calculation of quantity, \n or value."),
    ("firewood", "Wood used as fuel for a \n fire."),
    ("gigantic", "Of very great size or \n extent; huge."),
    ("hospital", "An institution for \n medical treatment."),
    ("identify", "To recognize or \n establish as being a \n particular person or \n thing."),
    ("jealousy", "Feelings of envy or \n insecurity over someone's \n advantages."),
    ("landlord", "A person who rents out \n land or buildings."),
    ("marathon", "A long-distance running \n race of 42.195 \n kilometers."),
    ("nickname", "A familiar or humorous \n name given to a person."),
    ("optimize", "To make the best or \n most effective use of \n something."),
    ("proclaim", "To announce officially \n or publicly."),
    ("question", "A sentence or phrase \n used to find out \n information."),
    ("recharge", "To restore electrical \n energy to a device."),
    ("scenery", "The natural features of \n a landscape."),
    ("treasure", "Valuable items such as \n gold, jewels, or \n antiques."),
    ("ultimate", "Being or happening at \n the end of a process; \n final."),
    ("validate", "To check or prove the \n accuracy of something."),
    ("workshop", "A place where manual \n work is done or a meeting \n for discussion."),
    ("abstract", "Existing in thought or \n as an idea but not \n having a physical \n reality."),
    ("ballroom", "A large room used for \n dancing."),
    ("cabbages", "A type of vegetable \n with dense leaves."),
    ("daydream", "A pleasant visionary \n creation of the \n imagination."),
    ("elephant", "A large mammal with a \n trunk."),
    ("football", "A team sport played \n with a round ball."),
    ("goodness", "The quality of being \n morally good."),
    ("handmade", "Made by hand, not by \n machine."),
    ("intended", "Planned or meant to \n occur."),
    ("jeopardy", "Exposure to danger or \n risk."),
    ("learning", "The acquisition of \n knowledge or skills."),
    ("medicine", "A substance used for \n treating illness or \n disease."),
    ("navigate", "To plan and direct the \n course of a ship, aircraft \n or other vehicle."),
    ("operator", "A person who operates \n equipment or a machine."),
    ("pinnacle", "The most successful \n point; the culmination."),
    ("quaintly", "In an attractively \n unusual or old-fashioned \n manner."),
    ("reliable", "Consistently good in \n quality or performance."),
    ("sunshine", "Direct sunlight \n unclouded by other \n weather conditions."),
    ("thorough", "Carried out with \n careful attention to \n detail."),
    ("umbrella", "A device used to \n protect from rain."),
    ("velocity", "Speed with direction, \n the rate of change of \n position."),
    ("workflow", "The sequence of steps \n involved in a process."),
    ("accident", "An unforeseen event, \n especially one causing \n damage or injury."),
    ("boomerang", "A curved tool designed \n to return to the thrower."),
    ("clothing", "Garments collectively; \n clothes."),
    ("download", "To transfer data from \n one computer to \n another."),
    ("evaluate", "To judge or calculate \n the quality, importance, \n or value of something."),
    ("fragment", "A small part broken \n off or separated."),
    ("glorious", "Having, worthy of, or \n bringing fame or honor."),
    ("heritage", "Valued objects and \n qualities passed down \n from previous \n generations."),
    ("identify", "To establish or \n recognize someone or \n something."),
    ("jacketed", "Covered with or \n enclosed in a jacket."),
    ("luminous", "Emitting or reflecting \n light."),
    ("mobility", "The ability to move or \n be moved freely."),
    ("narrator", "A person who tells a \n story."),
    ("outreach", "The process of reaching \n out to people."),
    ("prospect", "The possibility or \n likelihood of some future \n event occurring."),
    ("question", "A sentence asking for \n information."),
    ("resource", "A stock or supply of \n money, materials, staff, \n or other assets."),
    ("security", "The state of being \n free from danger or \n threat."),
    ("triangle", "A three-sided \n polygon."),
    ("umbrella", "A device used for \n protection against rain \n or sunlight."),
    ("vacation", "An extended period of \n leisure or recreation."),
    ("wildlife", "Animals living and \n growing in natural \n conditions."),
    ("yardstick", "A standard used for \n comparison or \n measurement."),
    ("balloons", "Inflatable rubber or \n plastic toys."),
    ("children", "Young human beings \n below the age of \n puberty."),
    ("diligent", "Showing care and \n conscientiousness in \n one's work."),
    ("enlarged", "Made larger; having \n increased in size."),
    ("feedback", "Information given in \n response to a product."),
    ("gradient", "An inclined part of a \n road or railway."),
    ("habitant", "An inhabitant or \n resident of a place."),
    ("illusion", "A false idea or \n belief."),
    ("juggling", "The activity of \n continuously tossing \n and catching objects."),
    ("learning", "The acquisition of \n knowledge or skills."),
    ("maximize", "To increase to the \n greatest possible \n amount."),
    ("notation", "A system of symbols \n used to represent \n numbers or quantities."),
    ("optimize", "To make the best or \n most effective use of."),
    ("pandemic", "A disease prevalent \n over a whole country or \n the world."),
    ("quicksand", "Loose wet sand that \n sucks in anything \n resting on it."),
    ("recharge", "To restore electrical \n energy to a device."),
    ("shoulder", "The upper joint of the \n human arm."),
    ("thirteen", "The number following \n twelve."),
    ("universe", "All existing matter \n and space considered as \n a whole."),
    ("velocity", "The speed of something \n in a given direction."),
    ("waterway", "A river, canal, or \n other route for travel."),
    ("xenolith", "A piece of rock \n different from the main \n type around it."),
    ("yardwork", "Physical work done in \n a yard, such as mowing \n grass."),
    ("zookeeper", "A person who manages \n and cares for animals in \n a zoo."),("absolutely", "Completely or totally \n sure."),
    ("benevolent", "Well-meaning and \n kindly; charitable."),
    ("calibration", "The process of \n adjusting an instrument \n for accuracy."),
    ("declaration", "An announcement or \n formal statement."),
    ("effortless", "Requiring no physical \n or mental exertion."),
    ("fascinated", "Strongly attracted or \n interested."),
    ("generosity", "Willingness to give \n and share."),
    ("hospitable", "Friendly and welcoming \n to strangers."),
    ("illuminate", "To light up or make \n bright."),
    ("jeopardize", "To put someone or \n something in danger."),
    ("knowledgeable", "Intelligent and well-\n informed; possessing \n knowledge."),
    ("literature", "Written works, \n especially those \n considered of superior \n or lasting merit."),
    ("mastermind", "A person with an \n outstanding intellect, \n or who plans a complex \n scheme."),
    ("networking", "Interacting with \n others to exchange \n information and \n develop professional or \n social contacts."),
    ("organically", "In a natural or \n biological way."),
    ("photograph", "A picture made using a \n camera."),
    ("quantities", "Amounts or numbers of \n something."),
    ("rejuvenate", "To make someone look \n or feel younger."),
    ("satisfactory", "Meeting the required \n standards; adequate."),
    ("toleration", "Acceptance of the \n existence of differing \n views."),
    ("unbeliever", "A person who does not \n believe, especially in \n a particular religion."),
    ("ventilator", "A device for \n ventilating a room or \n for helping someone \n breathe."),
    ("wonderment", "A feeling of surprise \n mingled with admiration."),
    ("xenophobic", "Having a dislike of or \n prejudice against \n people from other \n countries."),
    ("yieldingly", "Giving way to the \n demands or pressure of \n others."),
    ("zoological", "Relating to the study \n of animals."),
    ("adaptation", "The process of \n changing to fit new \n conditions."),
    ("background", "The part of a scene or \n picture that is farthest \n from the viewer."),
    ("chivalrous", "Courteous and \n gallant, especially \n toward women."),
    ("dispatcher", "A person who sends out \n vehicles according to \n a schedule."),
    ("eliminator", "Something or someone \n that removes or gets \n rid of something."),
    ("forethought", "Careful consideration \n of what will be \n necessary or may happen \n in the future."),
    ("graciously", "In a courteous, kind, \n and pleasant manner."),
    ("harmonious", "Forming a pleasing or \n consistent whole."),
    ("impressive", "Evoking admiration \n through size, quality, \n or skill."),
    ("journalism", "The activity of \n writing for newspapers, \n magazines, or news \n websites."),
    ("kaleidoscope", "A toy consisting of a \n tube containing mirrors \n and colored glass."),
    ("livelihood", "A means of securing \n the necessities of \n life."),
    ("memorandum", "A written message, \n especially in business \n or diplomacy."),
    ("nourishing", "Providing substances \n necessary for growth, \n health, and good \n condition."),
    ("operational", "In or ready for use."),
    ("prediction", "A statement about what \n will happen in the \n future."),
    ("quarantine", "A period of isolation \n to prevent the spread \n of disease."),
    ("reputation", "The beliefs or \n opinions that are \n generally held about \n someone."),
    ("stimulation", "Encouragement of \n something to make it \n active."),
    ("turbulence", "Violent or unsteady \n movement of air or \n water."),
    ("utilitarian", "Designed to be useful \n or practical rather \n than attractive."),
    ("vocabulary", "The body of words used \n in a particular \n language."),
    ("warranties", "Written guarantees, \n issued to the purchaser \n of an article."),
    ("xenogenesis", "The supposed creation \n of offspring that is \n markedly different from \n its parents."),
    ("yearningly", "With intense longing \n or desire."),
    ("zygopteran", "Belonging to a group \n of slender-bodied \n damselflies."),
    ("attraction", "A quality or feature \n that evokes interest, \n liking, or desire."),
    ("befuddling", "Confusing or perplexing."),
    ("chandelier", "A decorative hanging \n light with branches."),
    ("downstream", "In the direction in \n which a stream or river \n flows."),
    ("exhibition", "A public display of \n works of art or items \n of interest."),
    ("friendship", "A state of mutual \n trust and support \n between friends."),
    ("governance", "The action or manner \n of governing."),
    ("highlighted", "Emphasized or made \n prominent."),
    ("influences", "The capacity to have \n an effect on someone \n or something."),
    ("justifying", "Showing or proving \n to be right or \n reasonable."),
    ("knowledge", "Facts, information, or \n skills acquired by a \n person."),
    ("languishing", "Failing to make \n progress or be \n successful."),
    ("motivating", "Providing a reason \n for someone to do \n something."),
    ("negotiator", "A person who conducts \n negotiations."),
    ("opposition", "Resistance or \n dissent."),
    ("perception", "The ability to see, \n hear, or become aware \n of something."),
    ("questioner", "A person who asks \n questions."),
    ("radiometer", "An instrument for \n detecting or measuring \n radiant energy."),
    ("sponsoring", "Supporting a person, \n organization, or \n activity financially."),
    ("transcribe", "To put thoughts, \n speech, or data into \n written form."),
    ("undulating", "Moving with a smooth \n wavelike motion."),
    ("validation", "The action of checking \n or proving the accuracy \n of something."),
    ("wholesome", "Conducive to or \n suggestive of good \n health."),
    ("xenophobes", "People who dislike or \n are prejudiced against \n foreigners."),
    ("yesteryear", "Last year or the \n recent past."),
    ("zealously", "With great energy or \n enthusiasm."),
    ("absorption", "The process by which \n one thing absorbs or \n is absorbed by \n another."),
    ("bricklayer", "A person who builds \n with bricks."),
    ("chattering", "Talking rapidly or \n incessantly about \n trivial matters."),
    ("dispatcher", "A person who sends out \n vehicles according to \n a schedule."),
    ("elevations", "Heights above a given \n level, especially sea \n level."),
    ("formidable", "Inspiring fear or \n respect through being \n impressively large."),
    ("gratifying", "Giving pleasure or \n satisfaction."),
    ("harbingers", "People or things that \n announce or signal the \n approach of another."),
    ("inhabitant", "A person or animal \n that lives in a place."),
    ("justifying", "Showing or proving \n to be right or \n reasonable."),
    ("knowledge", "Facts, information, \n or skills acquired by \n a person."),
    ("lengthwise", "In the direction of \n the length."),
    ("management", "The process of dealing \n with or controlling \n things or people."),
    ("navigators", "People who direct the \n route or course of a \n ship or other vehicle."),
    ("organizing", "Arranging into a \n structured whole; \n order."),
    ("purchasing", "The action of buying \n something."),
    ("quicksands", "A bed of loose sand \n that yields easily to \n pressure and tends to \n suck down any object."),
    ("resonating", "Producing or be filled \n with a deep, full, \n reverberating sound."),
    ("submitting", "Presenting a proposal, \n application, or other \n document for \n consideration."),
    ("thresholds", "The magnitude or \n intensity that must be \n exceeded for a certain \n reaction."),
    ("ultimately", "Finally; in the end."),
    ("vulgarisms", "Common or crude \n expressions."),
    ("windlasses", "Machines used for \n moving heavy weights."),
    ("xenocrysts", "Crystals that are \n foreign to the igneous \n rock in which they are \n found."),
    ("youngsters", "Children or young \n people."),
    ("zoologists", "Scientists who study \n animals."),
    ("achievement", "A thing done \n successfully with effort, \n skill, or courage."),
    ("biological", "Relating to biology or \n living organisms."),
    ("championship", "A contest for the \n position of champion."),
    ("deliverance", "The action of being \n rescued or set free."),
    ("endorsement", "An act of giving \n one's public approval or \n support."),
    ("fellowship", "Friendly association, \n especially with people \n who share interests."),
    ("greenhouse", "A glass building in \n which plants are grown."),
    ("householder", "A person who owns or \n rents a house."),
    ("journalism", "The activity of \n gathering, assessing, \n creating, and \n presenting news."),
    ("knowledge", "Facts, information, or \n skills acquired by a \n person."),
    ("limitation", "A limiting rule or \n circumstance."),
    ("methodical", "Done according to a \n systematic or \n established form of \n procedure."),
    ("networking", "The action or process \n of interacting with \n others to exchange \n information."),
    ("obligation", "An act or course of \n action to which a \n person is morally or \n legally bound."),
    ("persuasive", "Good at persuading \n someone to do or \n believe something."),
    ("quiescence", "A state of being \n inactive or dormant."),
    ("relaxation", "The state of being \n free from tension and \n anxiety."),
    ("struggling", "Striving to achieve or \n attain something in the \n face of difficulty."),
    ("transaction", "An instance of buying \n or selling something; a \n business deal."),
    ("utilizable", "Capable of being put \n to use; useful."),
    ("vociferous", "Expressing or \n characterized by \n vehement opinions."),
    ("weightless", "Not affected by \n gravity."),
    ("xenolithic", "Related to a piece of \n rock that differs from \n the main rock in which \n it is embedded."),
    ("yearningly", "With strong desire or \n longing."),
    ("zealotries", "Fanatical devotion to a \n cause."))
    return tupl_word
    
lis_word=liswor()
l0=Label(root,text="HANGMAN GAME",font=("arial",20),bg="lightgreen").grid(row=0,column=1,pady=10,columnspan=3)
l1=Label(root,text="Guess the correct word:-",font=("arial",17),bg="lightblue").grid(row=1,column=1,pady=10)
l2=Label(root,text="Lives:",font=('arial',17),bg="lightblue").grid(row=1,column=2,pady=10,padx=20)
l21=Label(root,text=lives,font=('arial',19),bg="red").grid(row=1,column=3,pady=10,padx=20)
l3=Label(root,text=" In this game you have to guess the word \n The description of the word will be given \n a few letters of the word will be given \n guess the correct word in 10 attempts \n press NEW GAME to start new game",font=("arial",14),bg="lightblue")
l3.grid(row=3,column=1,pady=10,ipady=7,ipadx=10)
l4=Label(root,text=blank,font=("arial",14),bg="white").grid(row=4,column=1,pady=10)
l5=Label(root,text=blank,font=('arial',14),bg="white").grid(row=5,column=1,pady=10,padx=20)
ent1=Entry(root,bg="white",bd=7,font=25,justify="right",insertwidth=4)
ent1.grid(row=2,column=1,padx=20,ipady=10)

def ent_func():
    global l4,l5,lives,key,l21,l3
    value=ent1.get()
    try:
        if value.lower()==actual_word[0]:
            l4=Label(root,text=blank,font=("arial",14),bg="white").grid(row=4,column=1,pady=10)
            l5=Label(root,text=blank,font=('arial',14),bg="white").grid(row=5,column=1,pady=10,padx=20)
            l4=Label(root,text=(actual_word[0].upper()+" :Meaning :- \n"+actual_word[1]),font=("arial",14),bg="white").grid(row=4,column=1,pady=10,ipadx=16)
            l5=Label(root,text=("CONGRATULATIONS!! 🥳🤩\n YOU WON ! You guessed the word\n "),font=("arial",14),bg="white").grid(row=5,column=1,pady=10)
            lives=10
            l21=Label(root,text=lives,font=('arial',19),bg="red").grid(row=1,column=3,pady=10,padx=20)        
        else:
            ent1.delete(0,END)
            l5=Label(root,text=blank,font=('arial',14),bg="white").grid(row=5,column=1,pady=10,padx=20)
            l5=Label(root,text=("SORRY !! Word not matched !!\n "),font=("arial",14),bg="white").grid(row=5,column=1,pady=10)
            lives=lives-1
            l21=Label(root,text=lives,font=('arial',19),bg="red").grid(row=1,column=3,pady=10,padx=20)
            if lives==0:
                l4=Label(root,text=blank,font=("arial",14),bg="white").grid(row=4,column=1,pady=10)
                l5=Label(root,text=blank,font=('arial',14),bg="white").grid(row=5,column=1,pady=10,padx=20)
                l4=Label(root,text=(actual_word[0].upper()+" :Meaning :- \n"+actual_word[1]),font=("arial",14),bg="white").grid(row=4,column=1,pady=10,ipadx=16)
                l5=Label(root,text=("SORRY !! You are a loser !! 😝😛\n You lost everything in the game "),font=("arial",14),bg="white").grid(row=5,column=1,pady=10)
                key.destroy()
                key=Button(root,text="ENTER",bd=6,bg="yellow",font=("algerian",16)).grid(row=2,column=2,columnspan=2,padx=20) 
    except:
        ent1.delete(0,END)
        l4=Label(root,text=("Please start NEW GAME first !!"),font=("arial",14),bg="white").grid(row=4,column=1,pady=10)
def new_game():
    global l3,l4,l5,actual_word,l21,key,blank,ent1
    ent1.delete(0,END)
    actual_word,s=rnd.choice(lis_word),""
    ls=list(range(0,len(actual_word[0])))
    for i in range(0,len(actual_word[0])//2):
        j=rnd.choice(ls)
        ls.remove(j)
    for k in range(0,len(actual_word[0])):
        if k in ls:
            s+="_."
        else:
            s+=actual_word[0][k]
    l4=Label(root,text=blank,font=("arial",14),bg="white").grid(row=4,column=1,pady=10)
    l5=Label(root,text=blank,font=('arial',14),bg="white").grid(row=5,column=1,pady=10,padx=20)
    l4=Label(root,text=("The word is:- "+s+"\nMeaning:- "+actual_word[1]),font=("arial",14),bg="white").grid(row=4,column=1,pady=10,ipadx=16)
    #l5=Label(root,text=("Meaning:- "+actual_word[1]),font=("arial",14),bg="white").grid(row=5,column=1,pady=10)
    l21=Label(root,text="10",font=('arial',19),bg="red").grid(row=1,column=3,pady=10,padx=20)
    key=Button(root,text="ENTER",bd=6,bg="yellow",font=("algerian",16),command=ent_func)
    key.grid(row=2,column=2,columnspan=2,padx=20)

key=Button(root,text="ENTER",bd=6,bg="yellow",font=("algerian",16),command=ent_func)
key.grid(row=2,column=2,columnspan=2,padx=20)
newgam=Button(root,text="NEW GAME",bd=6,bg="yellow",font=("algerian",13),command=new_game).grid(row=3,column=2,columnspan=2,padx=20,ipadx=5)
l6=Label(root,text="Developer:- Kunal Kashyap",font=('arial',14),bg="lightblue").grid(row=6,column=1,columnspan=3)
l7=Label(root,text="© Copyleft Reserved: KKindustries pvt.ltd",font=('arial',14),bg="lightblue").grid(row=7,column=1,columnspan=3)
root.resizable(True,True)
root.geometry("750x760")
root.mainloop()